#!/bin/bash

# from https://www.youtube.com/watch?v=VJC6OpGpq0Y

clear

for f in {1..40}
do
	vcgencmd measure_temp
	sysbench --test=cpu --cpu-max-prime=25000 --num-threads=4 run >/dev/null 2>&1
done

vcgencmd measure_temp
